#!/bin/sh

# Ispell compatibility script for Enchant

command=""

for p 
do
  case $p in 
  -a|-A|-l|-c|-e*|-v*|-D) command=$p ;; 
  -*                    ) ;;
  *                     ) command=${command:="-"} ;;
  esac
done

case $command in
-A|-c|-e*|-d) echo "Enchant does not support the $command mode.";;
-a|-l|-v*   ) exec enchant "$@" ;;
"-"         ) exec enchant "$@" ;;
*           ) echo "Ispell compatibility script for Enchant."
              echo "Usage: $0 [options] -a|-l|-v[v]|<file>"
              exit 1 ;;
esac
