var hierarchy =
[
    [ "AppleSpellChecker", "classAppleSpellChecker.html", null ],
    [ "AppleSpellDictionary", "structAppleSpellDictionary.html", null ],
    [ "enchant::Broker", "classenchant_1_1Broker.html", null ],
    [ "enchant::Dict", "classenchant_1_1Dict.html", null ],
    [ "DictionaryDescription", "structDictionaryDescription.html", null ],
    [ "EnchantDictPrivateData", "structEnchantDictPrivateData.html", null ],
    [ "EnchantSession", "structEnchantSession.html", null ],
    [ "EnchantTestFixture", "structEnchantTestFixture.html", [
      [ "EnchantBrokerNoProvidersTestFixture", "structEnchantBrokerNoProvidersTestFixture.html", null ],
      [ "EnchantBrokerNoProvidersTestFixture", "structEnchantBrokerNoProvidersTestFixture.html", null ],
      [ "EnchantBrokerTestFixture", "structEnchantBrokerTestFixture.html", [
        [ "EnchantBrokerDescribeTestFixtureBase", "structEnchantBrokerDescribeTestFixtureBase.html", [
          [ "EnchantBrokerDescribeTestFixture", "structEnchantBrokerDescribeTestFixture.html", null ],
          [ "EnchantBrokerDescribeTestFixture", "structEnchantBrokerDescribeTestFixture.html", null ],
          [ "EnchantBrokerDescribe_ProviderHasInvalidUtf8Describe_TestFixture", "structEnchantBrokerDescribe__ProviderHasInvalidUtf8Describe__TestFixture.html", null ],
          [ "EnchantBrokerDescribe_ProviderHasInvalidUtf8Describe_TestFixture", "structEnchantBrokerDescribe__ProviderHasInvalidUtf8Describe__TestFixture.html", null ],
          [ "EnchantBrokerDescribe_ProviderHasInvalidUtf8Identify_TestFixture", "structEnchantBrokerDescribe__ProviderHasInvalidUtf8Identify__TestFixture.html", null ],
          [ "EnchantBrokerDescribe_ProviderHasInvalidUtf8Identify_TestFixture", "structEnchantBrokerDescribe__ProviderHasInvalidUtf8Identify__TestFixture.html", null ],
          [ "EnchantBrokerDescribe_ProviderLacksDescribe_TestFixture", "structEnchantBrokerDescribe__ProviderLacksDescribe__TestFixture.html", null ],
          [ "EnchantBrokerDescribe_ProviderLacksDescribe_TestFixture", "structEnchantBrokerDescribe__ProviderLacksDescribe__TestFixture.html", null ],
          [ "EnchantBrokerDescribe_ProviderLacksIdentify_TestFixture", "structEnchantBrokerDescribe__ProviderLacksIdentify__TestFixture.html", null ],
          [ "EnchantBrokerDescribe_ProviderLacksIdentify_TestFixture", "structEnchantBrokerDescribe__ProviderLacksIdentify__TestFixture.html", null ]
        ] ],
        [ "EnchantBrokerDescribeTestFixtureBase", "structEnchantBrokerDescribeTestFixtureBase.html", null ],
        [ "EnchantBrokerDictExists_ProviderImplementsAll_TestFixture", "structEnchantBrokerDictExists__ProviderImplementsAll__TestFixture.html", null ],
        [ "EnchantBrokerDictExists_ProviderImplementsAll_TestFixture", "structEnchantBrokerDictExists__ProviderImplementsAll__TestFixture.html", null ],
        [ "EnchantBrokerDictExists_ProviderImplementsDictionaryExist_TestFixture", "structEnchantBrokerDictExists__ProviderImplementsDictionaryExist__TestFixture.html", null ],
        [ "EnchantBrokerDictExists_ProviderImplementsDictionaryExist_TestFixture", "structEnchantBrokerDictExists__ProviderImplementsDictionaryExist__TestFixture.html", null ],
        [ "EnchantBrokerDictExists_ProviderImplementsListDictionaries_TestFixture", "structEnchantBrokerDictExists__ProviderImplementsListDictionaries__TestFixture.html", null ],
        [ "EnchantBrokerDictExists_ProviderImplementsListDictionaries_TestFixture", "structEnchantBrokerDictExists__ProviderImplementsListDictionaries__TestFixture.html", null ],
        [ "EnchantBrokerFreeAlternativeDisposeTestFixture", "structEnchantBrokerFreeAlternativeDisposeTestFixture.html", null ],
        [ "EnchantBrokerFreeAlternativeDisposeTestFixture", "structEnchantBrokerFreeAlternativeDisposeTestFixture.html", null ],
        [ "EnchantBrokerFreeDictAlternativeDisposeTestFixture", "structEnchantBrokerFreeDictAlternativeDisposeTestFixture.html", null ],
        [ "EnchantBrokerFreeDictAlternativeDisposeTestFixture", "structEnchantBrokerFreeDictAlternativeDisposeTestFixture.html", null ],
        [ "EnchantBrokerFreeDictTestFixture", "structEnchantBrokerFreeDictTestFixture.html", null ],
        [ "EnchantBrokerFreeDictTestFixture", "structEnchantBrokerFreeDictTestFixture.html", null ],
        [ "EnchantBrokerFreeTestFixture", "structEnchantBrokerFreeTestFixture.html", null ],
        [ "EnchantBrokerFreeTestFixture", "structEnchantBrokerFreeTestFixture.html", null ],
        [ "EnchantBrokerListDictionaries_TestFixtureBase", "structEnchantBrokerListDictionaries__TestFixtureBase.html", [
          [ "EnchantBrokerListDictionaries_ProviderDuplicateTags_TestFixture", "structEnchantBrokerListDictionaries__ProviderDuplicateTags__TestFixture.html", null ],
          [ "EnchantBrokerListDictionaries_ProviderDuplicateTags_TestFixture", "structEnchantBrokerListDictionaries__ProviderDuplicateTags__TestFixture.html", null ],
          [ "EnchantBrokerListDictionaries_TestFixture", "structEnchantBrokerListDictionaries__TestFixture.html", null ],
          [ "EnchantBrokerListDictionaries_TestFixture", "structEnchantBrokerListDictionaries__TestFixture.html", null ]
        ] ],
        [ "EnchantBrokerListDictionaries_TestFixtureBase", "structEnchantBrokerListDictionaries__TestFixtureBase.html", null ],
        [ "EnchantBrokerRequestDictionaryWithPwl_TestFixture", "structEnchantBrokerRequestDictionaryWithPwl__TestFixture.html", null ],
        [ "EnchantBrokerRequestDictionaryWithPwl_TestFixture", "structEnchantBrokerRequestDictionaryWithPwl__TestFixture.html", null ],
        [ "EnchantBrokerRequestDictionary_TestFixture", "structEnchantBrokerRequestDictionary__TestFixture.html", null ],
        [ "EnchantBrokerRequestDictionary_TestFixture", "structEnchantBrokerRequestDictionary__TestFixture.html", null ],
        [ "EnchantBrokerRequestPwlDictionary_TestFixture", "structEnchantBrokerRequestPwlDictionary__TestFixture.html", null ],
        [ "EnchantBrokerRequestPwlDictionary_TestFixture", "structEnchantBrokerRequestPwlDictionary__TestFixture.html", null ],
        [ "EnchantBrokerSetErrorTests", "structEnchantBrokerSetErrorTests.html", null ],
        [ "EnchantBrokerSetErrorTests", "structEnchantBrokerSetErrorTests.html", null ],
        [ "EnchantBrokerSetOrdering_TestFixture", "structEnchantBrokerSetOrdering__TestFixture.html", [
          [ "EnchantBrokerFileSetOrdering_TestFixture", "structEnchantBrokerFileSetOrdering__TestFixture.html", null ],
          [ "EnchantBrokerFileSetOrdering_TestFixture", "structEnchantBrokerFileSetOrdering__TestFixture.html", null ]
        ] ],
        [ "EnchantBrokerSetOrdering_TestFixture", "structEnchantBrokerSetOrdering__TestFixture.html", null ],
        [ "EnchantDictionaryTestFixture", "structEnchantDictionaryTestFixture.html", [
          [ "EnchantDictFreeStringList_TestFixture", "structEnchantDictFreeStringList__TestFixture.html", null ],
          [ "EnchantDictFreeStringList_TestFixture", "structEnchantDictFreeStringList__TestFixture.html", null ],
          [ "EnchantDictionaryAddToSessionNotImplemented_TestFixture", "structEnchantDictionaryAddToSessionNotImplemented__TestFixture.html", null ],
          [ "EnchantDictionaryAddToSessionNotImplemented_TestFixture", "structEnchantDictionaryAddToSessionNotImplemented__TestFixture.html", null ],
          [ "EnchantDictionaryAddToSession_TestFixture", "structEnchantDictionaryAddToSession__TestFixture.html", null ],
          [ "EnchantDictionaryAddToSession_TestFixture", "structEnchantDictionaryAddToSession__TestFixture.html", null ],
          [ "EnchantDictionaryCheckNotImplemented_TestFixture", "structEnchantDictionaryCheckNotImplemented__TestFixture.html", null ],
          [ "EnchantDictionaryCheckNotImplemented_TestFixture", "structEnchantDictionaryCheckNotImplemented__TestFixture.html", null ],
          [ "EnchantDictionaryCheck_TestFixture", "structEnchantDictionaryCheck__TestFixture.html", null ],
          [ "EnchantDictionaryCheck_TestFixture", "structEnchantDictionaryCheck__TestFixture.html", null ],
          [ "EnchantDictionaryDescribe_TestFixtureBase", "structEnchantDictionaryDescribe__TestFixtureBase.html", [
            [ "EnchantDictionaryDescribe_TestFixture", "structEnchantDictionaryDescribe__TestFixture.html", null ],
            [ "EnchantDictionaryDescribe_TestFixture", "structEnchantDictionaryDescribe__TestFixture.html", null ]
          ] ],
          [ "EnchantDictionaryDescribe_TestFixtureBase", "structEnchantDictionaryDescribe__TestFixtureBase.html", null ],
          [ "EnchantDictionaryGetExtraWordCharactersTestFixtureBase", "structEnchantDictionaryGetExtraWordCharactersTestFixtureBase.html", [
            [ "EnchantDictionaryGetExtraWordCharactersNotImplemented_TestFixture", "structEnchantDictionaryGetExtraWordCharactersNotImplemented__TestFixture.html", null ],
            [ "EnchantDictionaryGetExtraWordCharactersNotImplemented_TestFixture", "structEnchantDictionaryGetExtraWordCharactersNotImplemented__TestFixture.html", null ],
            [ "EnchantDictionaryGetExtraWordCharacters_TestFixture", "structEnchantDictionaryGetExtraWordCharacters__TestFixture.html", null ],
            [ "EnchantDictionaryGetExtraWordCharacters_TestFixture", "structEnchantDictionaryGetExtraWordCharacters__TestFixture.html", null ]
          ] ],
          [ "EnchantDictionaryGetExtraWordCharactersTestFixtureBase", "structEnchantDictionaryGetExtraWordCharactersTestFixtureBase.html", null ],
          [ "EnchantDictionaryIsAdded_TestFixture", "structEnchantDictionaryIsAdded__TestFixture.html", null ],
          [ "EnchantDictionaryIsAdded_TestFixture", "structEnchantDictionaryIsAdded__TestFixture.html", null ],
          [ "EnchantDictionaryIsRemoved_TestFixture", "structEnchantDictionaryIsRemoved__TestFixture.html", null ],
          [ "EnchantDictionaryIsRemoved_TestFixture", "structEnchantDictionaryIsRemoved__TestFixture.html", null ],
          [ "EnchantDictionaryIsWordCharacterTestFixtureBase", "structEnchantDictionaryIsWordCharacterTestFixtureBase.html", [
            [ "EnchantDictionaryIsWordCharacterNotImplemented_TestFixture", "structEnchantDictionaryIsWordCharacterNotImplemented__TestFixture.html", null ],
            [ "EnchantDictionaryIsWordCharacterNotImplemented_TestFixture", "structEnchantDictionaryIsWordCharacterNotImplemented__TestFixture.html", null ],
            [ "EnchantDictionaryIsWordCharacter_TestFixture", "structEnchantDictionaryIsWordCharacter__TestFixture.html", null ],
            [ "EnchantDictionaryIsWordCharacter_TestFixture", "structEnchantDictionaryIsWordCharacter__TestFixture.html", null ]
          ] ],
          [ "EnchantDictionaryIsWordCharacterTestFixtureBase", "structEnchantDictionaryIsWordCharacterTestFixtureBase.html", null ],
          [ "EnchantDictionaryRemoveFromSession_TestFixture", "structEnchantDictionaryRemoveFromSession__TestFixture.html", null ],
          [ "EnchantDictionaryRemoveFromSession_TestFixture", "structEnchantDictionaryRemoveFromSession__TestFixture.html", null ],
          [ "EnchantDictionaryRemoveNotImplemented_TestFixture", "structEnchantDictionaryRemoveNotImplemented__TestFixture.html", null ],
          [ "EnchantDictionaryRemoveNotImplemented_TestFixture", "structEnchantDictionaryRemoveNotImplemented__TestFixture.html", null ],
          [ "EnchantDictionaryRemove_TestFixture", "structEnchantDictionaryRemove__TestFixture.html", null ],
          [ "EnchantDictionaryRemove_TestFixture", "structEnchantDictionaryRemove__TestFixture.html", null ],
          [ "EnchantDictionarySetErrorTests", "structEnchantDictionarySetErrorTests.html", null ],
          [ "EnchantDictionarySetErrorTests", "structEnchantDictionarySetErrorTests.html", null ],
          [ "EnchantDictionarySuggestTestFixtureBase", "structEnchantDictionarySuggestTestFixtureBase.html", [
            [ "EnchantDictionarySuggestNotImplemented_TestFixture", "structEnchantDictionarySuggestNotImplemented__TestFixture.html", null ],
            [ "EnchantDictionarySuggestNotImplemented_TestFixture", "structEnchantDictionarySuggestNotImplemented__TestFixture.html", null ],
            [ "EnchantDictionarySuggest_TestFixture", "structEnchantDictionarySuggest__TestFixture.html", null ],
            [ "EnchantDictionarySuggest_TestFixture", "structEnchantDictionarySuggest__TestFixture.html", null ]
          ] ],
          [ "EnchantDictionarySuggestTestFixtureBase", "structEnchantDictionarySuggestTestFixtureBase.html", null ],
          [ "EnchantPwlWithDictSuggs_TestFixture", "structEnchantPwlWithDictSuggs__TestFixture.html", null ],
          [ "EnchantPwlWithDictSuggs_TestFixture", "structEnchantPwlWithDictSuggs__TestFixture.html", null ],
          [ "EnchantPwl_TestFixture", "structEnchantPwl__TestFixture.html", null ],
          [ "EnchantPwl_TestFixture", "structEnchantPwl__TestFixture.html", null ]
        ] ],
        [ "EnchantDictionaryTestFixture", "structEnchantDictionaryTestFixture.html", null ]
      ] ],
      [ "EnchantBrokerTestFixture", "structEnchantBrokerTestFixture.html", null ],
      [ "EnchantGetPrefixDirTestFixture", "structEnchantGetPrefixDirTestFixture.html", null ],
      [ "EnchantGetPrefixDirTestFixture", "structEnchantGetPrefixDirTestFixture.html", null ]
    ] ],
    [ "std::exception", null, [
      [ "enchant::Exception", "classenchant_1_1Exception.html", null ],
      [ "enchant::Exception", "classenchant_1_1Exception.html", null ]
    ] ],
    [ "HunspellChecker", "classHunspellChecker.html", null ],
    [ "Provider_TestFixture", "structProvider__TestFixture.html", [
      [ "DictionaryCheck_TestFixture", "structDictionaryCheck__TestFixture.html", null ],
      [ "DictionaryCheck_TestFixture", "structDictionaryCheck__TestFixture.html", null ],
      [ "DictionarySuggest_TestFixture", "structDictionarySuggest__TestFixture.html", null ],
      [ "DictionarySuggest_TestFixture", "structDictionarySuggest__TestFixture.html", null ],
      [ "ProviderDescribe_TestFixture", "structProviderDescribe__TestFixture.html", null ],
      [ "ProviderDescribe_TestFixture", "structProviderDescribe__TestFixture.html", null ],
      [ "ProviderDictionaryExists_TestFixture", "structProviderDictionaryExists__TestFixture.html", null ],
      [ "ProviderDictionaryExists_TestFixture", "structProviderDictionaryExists__TestFixture.html", null ],
      [ "ProviderIdentify_TestFixture", "structProviderIdentify__TestFixture.html", null ],
      [ "ProviderIdentify_TestFixture", "structProviderIdentify__TestFixture.html", null ],
      [ "ProviderListDicts_TestFixture", "structProviderListDicts__TestFixture.html", null ],
      [ "ProviderListDicts_TestFixture", "structProviderListDicts__TestFixture.html", null ],
      [ "ProviderRequestDictionary_TestFixture", "structProviderRequestDictionary__TestFixture.html", null ],
      [ "ProviderRequestDictionary_TestFixture", "structProviderRequestDictionary__TestFixture.html", null ]
    ] ],
    [ "ProviderDescription", "structProviderDescription.html", null ],
    [ "rpl_max_align_t", "unionrpl__max__align__t.html", null ],
    [ "str_enchant_broker", "structstr__enchant__broker.html", null ],
    [ "str_enchant_dict", "structstr__enchant__dict.html", null ],
    [ "str_enchant_provider", "structstr__enchant__provider.html", null ],
    [ "str_enchant_pwl", "structstr__enchant__pwl.html", null ],
    [ "Zemberek", "classZemberek.html", null ]
];