# options to filter out, and why
--all-warnings				alias for -Wall
--extra-warnings			alias for -Wextra
-frequire-return-statement		go
-Waggregate-return			obsolescent
-Waliasing				fortran
-Walign-commons				fortran
-Wampersand				fortran
-Warray-bounds				covered by -Warray-bounds=
-Warray-bounds=				handled specially by gl_MANYWARN_ALL_GCC
-Warray-temporaries			fortran
-Wassign-intercept			objc/objc++
-Wbad-function-cast			c
-Wc++0x-compat				c++ compatibility
-Wc++11-compat				c++ compatibility
-Wc++14-compat				c++ compatibility
-Wc90-c99-compat			c compatibility
-Wc99-c11-compat			c compatibility
-Wcast-qual				FIXME maybe? too much noise; encourages bad changes
-Wcast-result				d
-Wc-binding-type			fortran
-Wc++-compat				FIXME maybe? borderline.  some will want this
-Wcharacter-truncation			fortran
-Wcompare-reals				fortran
-Wconversion-extra			fortran
-Wconversion				FIXME maybe? too much noise; encourages bad changes
-Wdeclaration-after-statement		FIXME: do not want.  others may
-Wdesignated-init			c
-Wdiscarded-array-qualifiers		c
-Wdiscarded-qualifiers			c
-Werror-implicit-function-declaration	deprecated
-Wfloat-conversion			FIXME maybe? borderline.  some will want this
-Wfloat-equal				FIXME maybe? borderline.  some will want this
-Wformat				covered by -Wformat=2
-Wformat=				gcc --help=warnings artifact
-Wframe-larger-than=<number>		FIXME: choose something sane?
-Wfunction-elimination			fortran
-Wimplicit				c
-Wimplicit-function-declaration		c
-Wimplicit-int				c
-Wimplicit-interface			fortran
-Wimplicit-procedure			fortran
-Wincompatible-pointer-types		c
-Wint-conversion			c
-Winteger-division			fortran
-Wintrinsic-shadow			fortran
-Wintrinsics-std			fortran
-Wjump-misses-init			c
-Wlarger-than-				gcc --help=warnings artifact
-Wlarger-than=<number>			FIXME: choose something sane?
-Wline-truncation			fortran
-Wlong-long				obsolescent
-Wmissing-format-attribute		obsolescent
-Wmissing-noreturn			obsolescent
-Wmissing-parameter-type		c
-Wmissing-prototypes			c
-Wnested-externs			c
-Wnormalized				covered by -Wnormalized=
-Wnormalized=<none|id|nfc|nfkc>		handled specially by gl_MANYWARN_ALL_GCC
-Wold-style-declaration			c
-Wold-style-definition			c
-Woverride-init				c
-Wpadded				FIXME maybe?  warns about "stabil" member in /usr/include/bits/timex.h
-Wpedantic				FIXME: too strict?
-Wpointer-sign				c
-Wpointer-to-int-cast			c
-Wproperty-assign-default		objc++
-Wprotocol				objc++
-Wrealloc-lhs-all			fortran
-Wrealloc-lhs				fortran
-Wreal-q-constant			fortran
-Wredundant-decls			FIXME maybe? many _gl_cxxalias_dummy FPs
-Wselector				objc and objc++
-Wshadow-ivar				objc
-Wshift-overflow			covered by -Wshift-overflow=2
-Wshift-overflow=			gcc --help=warnings artifact
-Wsign-compare				FIXME maybe? borderline.  some will want this
-Wsign-conversion			FIXME maybe? borderline.  some will want this
-Wstack-usage=				FIXME: choose something sane?
-Wstrict-aliasing=			FIXME: choose something sane?
-Wstrict-overflow=			FIXME: choose something sane?
-Wstrict-prototypes			c
-Wstrict-selector-match			objc and objc++
-Wsurprising				fortran
-Wswitch-enum				FIXME maybe? borderline.  some will want this
-Wsynth					deprecated
-Wtabs					fortran
-Wtarget-lifetime			fortran
-Wtraditional-conversion		obsolescent
-Wtraditional				obsolescent
-Wundeclared-selector			objc and objc++
-Wundef					FIXME maybe? too many false positives
-Wunderflow				fortran
-Wunreachable-code			obsolescent no-op
-Wunsuffixed-float-constants		triggers warning in gnulib's timespec.h
-Wunused-const-variable			covered by -Wunusec-const-variable=2
-Wunused-const-variable=		gcc --help=warnings artifact
-Wunused-dummy-argument			fortran
-Wuse-without-only			fortran
-Wzerotrip				fortran
